services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stack-tutorial-web
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15-alpine
    container_name: stack-tutorial-db
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data:
